#!/usr/bin/env bash

# borrowed from btrfs-assistant
# see here: https://gitlab.com/btrfs-assistant/btrfs-assistant/-/blob/main/src/btrfs-assistant-launcher

# Define the base command with common options
command="pkexec cachyos-pi --xdg-runtime=\"${XDG_RUNTIME_DIR}\""

# Add xdg-desktop option if XDG_CURRENT_DESKTOP is set
if [[ -n ${XDG_CURRENT_DESKTOP} ]]; then
    command="${command} --xdg-desktop=\"${XDG_CURRENT_DESKTOP}\""
fi

# Add platform and display options when using Wayland
if [[ -n "${WAYLAND_DISPLAY}" ]]; then
    command="${command} --display=\"${WAYLAND_DISPLAY}\""
    if [[ -n "${QT_QPA_PLATFORM}" ]]; then
        command="${command} --platform=\"${QT_QPA_PLATFORM}\""
    fi
fi

if [[ -n "${DISPLAY}" ]]; then
    command="${command} --x11-display=\"${DISPLAY}\""
fi

# Add platformtheme option if QT_QPA_PLATFORMTHEME is set
if [[ -n ${QT_QPA_PLATFORMTHEME} ]]; then
    command="${command} --platformtheme=\"${QT_QPA_PLATFORMTHEME}\""
fi

# Add style-override option if QT_STYLE_OVERRIDE is set
if [[ -n ${QT_STYLE_OVERRIDE} ]]; then
    command="${command} --style-override=\"${QT_STYLE_OVERRIDE}\""
fi

# Add home path option if HOME is set
# fixes user theming
if [[ -n ${HOME} ]]; then
    command="${command} --home-path=\"${HOME}\""
fi

# Execute the constructed command
eval "$command"
